sudo: false

language: "python"

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - "pip install -U nose tox tox-travis"

script:
    - "tox"

notifications:
  email: false
